import type { AppState, SavedAtlasAPI, SavedMessage } from '../../shared/contracts'

const rows=[
  ['Курс по генеративному ИИ','Практический курс по GenAI от команды AI Learners. 12 модулей, 40+ уроков и реальные кейсы. Старт потока — 15 мая.','AI Learners','Курсы по ИИ','current'],
  ['Подборка инструментов для работы','Топ-20 сервисов для продуктивной работы с документами и исследованиями.','НейроНовости','ИИ-сервисы','current'],
  ['Статья: будущее AGI','Аналитика о перспективах автономных систем и их ограничениях.','Future Mind','Модели и исследования','uncertain'],
  ['Конспект книги','Ключевые мысли из книги об искусственном интеллекте и обществе.','Личное сообщение','Книги и конспекты','evergreen'],
  ['Новый релиз Claude','Обзор возможностей новой версии модели и примеры сценариев.','AI Inside','Модели и исследования','superseded'],
  ['Модели оценки LLM','Сравнение метрик, бенчмарков и методов человеческой оценки.','ML Papers','Модели и исследования','current'],
  ['Нейросети для дизайна','Лучшие инструменты для UI/UX из подборки 2023 года.','Design AI','ИИ-сервисы','outdated'],
  ['Промпт-инжиниринг 101','Базовые техники: роль, контекст, критерии результата и примеры.','Prompt Craft','ИИ-сервисы','evergreen']
] as const
const statuses:any=['current','outdated','superseded','unavailable','evergreen','uncertain','unchecked']
let messages:SavedMessage[]=rows.map((r,i)=>({id:i+1,telegramMessageId:5000-i,date:new Date(Date.now()-i*86400000).toISOString(),editDate:null,text:r[1],caption:'',sourceTitle:r[2],sourceUsername:null,sourcePublicUrl:i===0?'https://example.com/course':null,mediaType:'text',contentHash:`demo-${i}`,summary:`${r[0]}. ${r[1]}`,topicId:i===0?1:i===3?7:3,topicName:r[3],categoryName:i===3?'Обучение':'Искусственный интеллект',tags:i===0?['генеративный ИИ','курс','обучение']:['ИИ','материал'],freshnessStatus:statuses.includes(r[4])?r[4]:'unchecked',freshnessVerdict:i===0?'Курс доступен, программа и формат обучения актуальны.':'Материал проверен и сохранён в библиотеке.',freshnessReason:i===0?'Официальная страница содержит актуальную программу и даты ближайшего потока.':'Вывод основан на доступных источниках.',freshnessConfidence:i===2?0.58:0.9,citations:i===0?[{title:'Официальная страница курса',url:'https://example.com/course',claim:'Опубликованы программа и даты потока.'}]:[],analysisState:i===2?'review':'complete',userNote:'',isManual:false}))
const topics=[{id:1,categoryId:1,categoryName:'Искусственный интеллект',name:'Курсы по ИИ',description:'Учебные программы и практикумы',icon:'graduation-cap',messageCount:46,newCount:4,outdatedCount:7},{id:2,categoryId:1,categoryName:'Искусственный интеллект',name:'ИИ-сервисы',description:'Инструменты и приложения',icon:'wand',messageCount:31,newCount:2,outdatedCount:4},{id:3,categoryId:1,categoryName:'Искусственный интеллект',name:'Модели и исследования',description:'Модели, статьи и оценки',icon:'brain',messageCount:18,newCount:3,outdatedCount:2},{id:4,categoryId:2,categoryName:'Разработка',name:'Python',description:'Библиотеки и практика Python',icon:'code',messageCount:24,newCount:1,outdatedCount:1},{id:7,categoryId:3,categoryName:'Обучение',name:'Книги и конспекты',description:'Книги и личные конспекты',icon:'book',messageCount:16,newCount:1,outdatedCount:0}]
const state=():AppState=>({dashboard:{total:1248,topics:42,newCount:12,unprocessed:12,outdated:47,review:8,lastSyncAt:new Date().toISOString(),telegramConnected:true,routerConnected:true,demoMode:true},messages,topics})
export const mockApi:SavedAtlasAPI={getState:async()=>state(),search:async(input)=>messages.filter(m=>(!input.query||`${m.text} ${m.summary} ${m.sourceTitle}`.toLowerCase().includes(input.query.toLowerCase()))&&(!input.status||m.freshnessStatus===input.status)&&(!input.topicId||m.topicId===input.topicId)),sync:async()=>{await new Promise(r=>setTimeout(r,900));return{added:2,updated:1,analyzed:3,skipped:20,review:1,topicsCreated:0,freshnessChecks:2,failed:0}},changeTopic:async({messageId,topicId})=>{messages=messages.map(m=>m.id===messageId?{...m,topicId,topicName:topics.find(t=>t.id===topicId)?.name??m.topicName,isManual:true}:m)},saveNote:async({messageId,note})=>{messages=messages.map(m=>m.id===messageId?{...m,userNote:note}:m)},seedDemo:async()=>{},saveCredentials:async()=>{},saveTelegramCredentials:async()=>{},saveRouterSettings:async()=>{},credentialsStatus:async()=>({telegram:true,router:true}),telegramSendCode:async()=>({state:'code_sent'}),telegramSubmitCode:async()=>({state:'authorized'}),telegramSubmitPassword:async()=>({state:'authorized'}),telegramCancelAuth:async()=>{},testRouter:async()=>({ok:true,message:'Подключение работает.'}),exportJson:async()=>'/tmp/export.json',openExternal:async()=>{},resetData:async()=>{messages=[]},deleteSecrets:async()=>{}}
