import { describe, expect, it } from 'vitest'
import { Api } from 'telegram'
import { extractTelegramMessage, type EnrichedTelegramMessage } from '../src/main/services/sync'
import { parseRouterAnnotations } from '../src/main/services/routerai'

describe('Telegram metadata fixtures', () => {
  it('preserves a public forwarded post, caption, album, entities, and valid source URL', () => { const value = new Api.Message({ id: 77, peerId: new Api.PeerUser({ userId: BigInt(1) as any }), date: 1_700_000_000, message: 'Подпись к фото', media: new Api.MessageMediaPhoto({ photo: new Api.PhotoEmpty({ id: BigInt(10) as any }) }), entities: [new Api.MessageEntityBold({ offset: 0, length: 7 })], groupedId: BigInt(42) as any, fwdFrom: new Api.MessageFwdHeader({ date: 1_699_000_000, fromId: new Api.PeerChannel({ channelId: BigInt(99) as any }), channelPost: 123 }), out: false, mentioned: false, mediaUnread: false, silent: false, post: false, fromScheduled: false, legacy: false, editHide: false, pinned: false, noforwards: false } as any) as EnrichedTelegramMessage; value.savedAtlasSource = { peerId: '99', messageId: 123, title: 'Public Fixture', username: 'public_fixture', type: 'public_channel', publicUrl: 'https://t.me/public_fixture/123', originalPostDate: new Date(1_699_000_000_000).toISOString(), forwardingMetadata: { importedFromSavedMessages: true } }; const result = extractTelegramMessage(value); expect(result.caption).toBe('Подпись к фото'); expect(result.groupedId).toBe('42'); expect(result.entities).toHaveLength(1); expect(result.sourcePublicUrl).toBe('https://t.me/public_fixture/123'); expect(result.originalPostDate).toContain('2023') })
  it('never invents a public URL for a private or hidden source', () => { const value = new Api.Message({ id: 1, peerId: new Api.PeerUser({ userId: BigInt(1) as any }), date: 1_700_000_000, message: 'private', fwdFrom: new Api.MessageFwdHeader({ date: 1_699_000_000, fromName: 'Скрытый автор' }), out: false, mentioned: false, mediaUnread: false, silent: false, post: false, fromScheduled: false, legacy: false, editHide: false, pinned: false, noforwards: false } as any); const result = extractTelegramMessage(value); expect(result.sourceType).toBe('hidden_author'); expect(result.sourcePublicUrl).toBeNull() })
})

describe('RouterAI annotations', () => {
  it('parses realistic URL citation annotations and deduplicates URLs', () => { const annotations = parseRouterAnnotations({ annotations: [{ type: 'url_citation', url_citation: { title: 'Docs', url: 'https://example.com/docs', start_index: 10, end_index: 20 } }, { type: 'url_citation', url_citation: { title: 'Docs duplicate', url: 'https://example.com/docs' } }] }); expect(annotations).toEqual([{ title: 'Docs duplicate', url: 'https://example.com/docs', startIndex: undefined, endIndex: undefined }]) })
})
