import { afterEach, describe, expect, it } from 'vitest'
import { mkdtempSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { SavedAtlasDatabase } from '../src/main/database'
import { JobRunner } from '../src/main/services/job-runner'

const dirs: string[] = []
const makePath = () => { const dir = mkdtempSync(join(tmpdir(), 'savedatlas-queue-')); dirs.push(dir); return join(dir, 'db.sqlite') }
afterEach(() => { while (dirs.length) rmSync(dirs.pop()!, { recursive: true, force: true }) })
const imported = (id: number, text: string) => ({ telegramMessageId: id, date: new Date(1_700_000_000_000 + id * 1000).toISOString(), editDate: null, text, caption: '', mediaType: 'text', sourceTitle: 'Fixture', sourceUsername: null, sourcePublicUrl: null, rawJson: '{}' })
const classification = (id: number) => ({ message_id: id, summary: `Сводка ${id}`, content_type: 'note', category: { existing_id: null, proposed_name: null, confidence: .9 }, primary_topic: { existing_id: null, proposed_name: null, proposed_description: null, confidence: .9 }, tags: ['проверка'], language: 'ru', freshness_check_needed: false, freshness_reason: '', suggested_search_query: null, needs_review: false })

describe('persistent job runner and global FTS', () => {
  it('recovers a running job after restart and actually drains every dependency', async () => { const path = makePath(); const first = new SavedAtlasDatabase(path); first.importMessage(imported(1, 'Перезапускаемая очередь')); expect(first.claimJob()?.jobType).toBe('classification'); first.close(); const second = new SavedAtlasDatabase(path); const router = { classify: async ({ id }: { id: number }) => ({ value: classification(id), annotations: [] }), checkFreshness: async () => { throw new Error('not expected') } } as any; await new JobRunner(second, router, { sleep: async () => undefined }).start(); expect(second.countJobs('pending')).toBe(0); expect(second.countJobs('complete')).toBe(2); expect(second.searchMessages({ query: 'Сводка', limit: 10, offset: 0 }).total).toBe(1); second.close() })
  it('finds a record beyond the first 50 and paginates the complete result set', () => { const db = new SavedAtlasDatabase(makePath()); for (let id = 1; id <= 140; id += 1) db.importMessage(imported(id, id === 120 ? 'Уникальный далёкий маркер' : `Обычная запись ${id}`)); const page = db.searchMessages({ query: 'запись', limit: 50, offset: 50 }); expect(page.items).toHaveLength(50); expect(page.total).toBe(139); expect(db.searchMessages({ query: 'далёкий!!! маркер???', limit: 10, offset: 0 }).items[0].telegramMessageId).toBe(120); db.close() })
  it('updates FTS after AI classification, a note, and manual topic change', () => { const db = new SavedAtlasDatabase(makePath()); db.seedDemo(); const message = db.getState().messages[0]; db.applyClassification(message.id, { ...classification(message.id), summary: 'Совершенно уникальная сводка' }, { forceTopic: true }); expect(db.searchMessages({ query: 'уникальная сводка', limit: 10, offset: 0 }).total).toBe(1); db.saveNote(message.id, 'Секретный поисковый контекст'); expect(db.searchMessages({ query: 'поисковый контекст', limit: 10, offset: 0 }).total).toBe(1); db.changeTopic(message.id, 2); expect(db.searchMessages({ query: 'ИИ-сервисы', limit: 10, offset: 0 }).items.some((item) => item.id === message.id)).toBe(true); db.close() })
  it('keeps manual topic assignment after an edited Telegram message', () => { const db = new SavedAtlasDatabase(makePath()); db.seedDemo(); const message = db.getState().messages[0]; db.changeTopic(message.id, 2); db.importMessage({ ...imported(message.telegramMessageId, `${message.text} обновлено`), date: message.date }); expect(db.searchMessages({ topicId: 2, limit: 50, offset: 0 }).items.find((item) => item.id === message.id)?.isManual).toBe(true); db.close() })
  it('uses the real freshness cache, preserves annotation verification, and lets manual recheck bypass it', () => { const db = new SavedAtlasDatabase(makePath()); db.importMessage(imported(1, 'Версия сервиса зависит от времени')); const message = db.getState().messages[0]; const checked = new Date().toISOString(); db.applyFreshness(message.id, { status: 'current', verdict: 'Поддерживается', reason: 'Документация', confidence: .9, checked_at: checked, recommended_recheck_days: 30, alternatives: [{ name: 'Альтернатива', why: 'Другой вариант', url: 'https://example.com/alt', limitations: 'Ограничение', supporting_source_url: 'https://example.com/docs' }], citations: [{ title: 'Документация', url: 'https://example.com/docs', claim: 'Поддерживается' }, { title: 'Model only', url: 'https://example.com/unverified', claim: 'Не подтверждено API' }] }, [{ title: 'Документация', url: 'https://example.com/docs' }]); expect(db.scheduleFreshness(message.id)).toBeNull(); expect(db.scheduleFreshness(message.id, null, true)).toEqual(expect.any(Number)); const saved = db.searchMessages({ limit: 10, offset: 0 }).items[0]; expect(saved.citations.map((citation) => citation.verified)).toEqual([true, false]); expect(saved.alternatives[0].supportingSource?.title).toBe('Документация'); db.close() })
})
