import { afterEach, describe, expect, it } from 'vitest'
import { mkdtempSync, rmSync } from 'node:fs'
import { join } from 'node:path'
import { tmpdir } from 'node:os'
import { Api } from 'telegram'
import { SavedAtlasDatabase } from '../src/main/database'
import { SyncService } from '../src/main/services/sync'

const dirs: string[] = []
const makePath = () => { const dir = mkdtempSync(join(tmpdir(), 'savedatlas-sync-')); dirs.push(dir); return join(dir, 'db.sqlite') }
afterEach(() => { while (dirs.length) rmSync(dirs.pop()!, { recursive: true, force: true }) })
function message(id: number, text = `Сообщение ${id}`) { return new Api.Message({ id, peerId: new Api.PeerUser({ userId: BigInt(1) as any }), date: Math.floor(Date.now() / 1000), message: text, out: false, mentioned: false, mediaUnread: false, silent: false, post: false, fromScheduled: false, legacy: false, editHide: false, pinned: false, noforwards: false } as any) }
const range = (from: number, to: number) => Array.from({ length: from - to + 1 }, (_, index) => message(from - index))
const paged = (all: Api.Message[]) => ({ fetchSavedPage: async (offset: number, limit: number) => { const start = offset === 0 ? 0 : all.findIndex((item) => item.id < offset); return start < 0 ? [] : all.slice(start, start + limit) } })

describe('Telegram pagination and checkpoints', () => {
  it('imports 250 messages across three pages without an arbitrary cap', async () => { const db = new SavedAtlasDatabase(makePath()); const sync = new SyncService(paged(range(250, 1)) as any, db); const result = await sync.runFull(); expect(result.added).toBe(250); expect(sync.getProgress().pages).toBe(3); expect(db.getState().dashboard.total).toBe(250); expect(db.getSyncCheckpoint().lastKnownMessageId).toBe(250); db.close() })
  it('imports more than 100 new messages and reads a configured overlap', async () => { const db = new SavedAtlasDatabase(makePath()); await new SyncService(paged(range(250, 1)) as any, db).runFull(); const sync = new SyncService(paged(range(380, 1)) as any, db); const result = await sync.runIncremental(); expect(result.added).toBe(130); expect(sync.getProgress().pages).toBeGreaterThan(2); expect(db.getSyncCheckpoint().lastKnownMessageId).toBe(380); db.close() })
  it('resumes an interrupted full import from its durable page checkpoint', async () => { const path = makePath(); const firstDb = new SavedAtlasDatabase(path); const first = new SyncService({ fetchSavedPage: async (offset: number) => { if (offset === 0) return range(250, 151); throw new Error('NETWORK') } } as any, firstDb); expect((await first.runFull()).failed).toBe(1); expect(firstDb.getSyncCheckpoint().currentOffset).toBe(151); firstDb.close(); const secondDb = new SavedAtlasDatabase(path); const offsets: number[] = []; const second = new SyncService({ fetchSavedPage: async (offset: number, limit: number) => { offsets.push(offset); return paged(range(150, 1)).fetchSavedPage(offset === 151 ? 0 : offset, limit) } } as any, secondDb); await second.runFull(); expect(offsets[0]).toBe(151); expect(secondDb.getState().dashboard.total).toBe(250); expect(secondDb.getSyncCheckpoint().fullSyncComplete).toBe(true); secondDb.close() })
  it('detects an edited message inside the incremental overlap', async () => { const db = new SavedAtlasDatabase(makePath()); await new SyncService(paged(range(3, 1)) as any, db).runFull(); const edited = [message(3), message(2, 'Сообщение 2 — исправлено'), message(1)]; const result = await new SyncService(paged(edited) as any, db).runIncremental(); expect(result.updated).toBe(1); expect(db.searchMessages({ query: 'исправлено', limit: 10, offset: 0 }).total).toBe(1); db.close() })
  it('does not loop or duplicate records when Telegram repeats a page', async () => { const db = new SavedAtlasDatabase(makePath()); const all = range(250, 1); let repeated = false; const telegram = { fetchSavedPage: async (offset: number, limit: number) => { if (offset === 151 && !repeated) { repeated = true; return all.slice(0, 100) } return paged(all).fetchSavedPage(offset, limit) } }; const sync = new SyncService(telegram as any, db); await sync.runFull(); expect(db.getState().dashboard.total).toBe(250); expect(sync.getProgress().pages).toBe(4); db.close() })
  it('waits and retries after FloodWait without losing the checkpoint', async () => { const db = new SavedAtlasDatabase(makePath()); let calls = 0; let slept = 0; const sync = new SyncService({ fetchSavedPage: async () => { calls += 1; if (calls === 1) throw new Error('FLOOD_WAIT_2'); return calls === 2 ? [message(1)] : [] } } as any, db, { sleep: async (milliseconds) => { slept += milliseconds } }); const result = await sync.runFull(); expect(result.added).toBe(1); expect(slept).toBe(2000); expect(db.getSyncCheckpoint().lastKnownMessageId).toBe(1); db.close() })
})
