// @vitest-environment jsdom
import React from 'react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import '@testing-library/jest-dom/vitest'
import type { AppState, SavedAtlasAPI, SavedMessage } from '../src/shared/contracts'
import { mockApi } from '../src/renderer/src/mock'

afterEach(() => { cleanup(); vi.restoreAllMocks(); vi.resetModules() })
const topic = { id: 99, categoryId: 1, categoryName: 'Тест', name: 'Дальняя тема', description: 'Точная фильтрация', icon: 'book', messageCount: 1, newCount: 0, outdatedCount: 0 }
const item: SavedMessage = { id: 900, telegramMessageId: 900, date: new Date().toISOString(), editDate: null, originalPostDate: null, text: 'Материал за пределами первых пятидесяти', caption: '', sourceTitle: 'Fixture', sourceUsername: null, sourcePublicUrl: null, sourceType: 'personal_note', mediaType: 'text', mediaMetadata: {}, contentHash: 'hash', summary: 'Глобальный результат поиска.', topicId: 99, topicName: topic.name, categoryName: topic.categoryName, tags: ['поиск'], freshnessStatus: 'unchecked', freshnessVerdict: '', freshnessReason: '', freshnessConfidence: 0, citations: [], alternatives: [], analysisState: 'complete', userNote: '', isManual: false }
const makeState = (complete = true): AppState => ({ dashboard: { total: 1000, topics: 1, newCount: 1, current: 0, unprocessed: 0, outdated: 0, unchecked: 1000, review: 0, lastSyncAt: null, telegramConfigured: true, telegramAuthorized: true, routerConfigured: true, routerTested: true, demoMode: false }, setup: { complete, telegramAuthorized: true, routerConfigured: true }, messages: [], topics: [topic] })

async function load(api: SavedAtlasAPI) { window.savedAtlas = api; const { App } = await import('../src/renderer/src/App'); return render(<App />) }

describe('renderer workflows', () => {
  it('finishes real-mode setup, waits for full local import, then opens the library', async () => {
    let complete = false; const order: string[] = []
    const api: SavedAtlasAPI = { ...mockApi, getState: async () => makeState(complete), getSetupState: async () => ({ complete, telegramAuthorized: true, routerConfigured: true }), saveTelegramCredentials: async () => { order.push('telegram-settings') }, telegramSendCode: async () => ({ state: 'code_sent' }), telegramSubmitCode: async () => ({ state: 'authorized' }), saveRouterSettings: async () => { order.push('router-settings') }, completeSetup: async () => { order.push('setup-complete'); complete = true }, syncFull: async () => { order.push('full-sync'); return { added: 260, updated: 0, skipped: 0, failed: 0 } }, getSyncProgress: async () => ({ mode: 'full', state: 'complete', pages: 3, fetched: 260, added: 260, updated: 0, skipped: 0, latestKnownId: 260, checkpointOffset: 0, error: null }) }
    await load(api); fireEvent.click(await screen.findByRole('button', { name: 'Начать настройку' })); fireEvent.change(screen.getByLabelText('api_id'), { target: { value: '12345678' } }); fireEvent.change(screen.getByLabelText('api_hash'), { target: { value: 'a'.repeat(32) } }); fireEvent.click(screen.getByRole('button', { name: 'Продолжить' })); await screen.findByRole('heading', { name: 'Вход в Telegram' }); fireEvent.change(screen.getByLabelText('Номер телефона'), { target: { value: '+79990000000' } }); fireEvent.click(screen.getByRole('button', { name: 'Получить код' })); await screen.findByLabelText('Код из Telegram'); fireEvent.change(screen.getByLabelText('Код из Telegram'), { target: { value: '12345' } }); fireEvent.click(screen.getByRole('button', { name: 'Подтвердить' })); await screen.findByRole('heading', { name: 'Подключите RouterAI' }); fireEvent.change(screen.getByLabelText('RouterAI API key'), { target: { value: 'mock-key-for-tests-only' } }); fireEvent.click(screen.getByRole('button', { name: 'Продолжить' })); await screen.findByRole('heading', { name: 'Настройте анализ' }); fireEvent.click(screen.getByRole('button', { name: 'Завершить и синхронизировать' })); expect(await screen.findByText('Ваша библиотека сохранённых материалов')).toBeTruthy(); expect(order).toEqual(['telegram-settings', 'router-settings', 'setup-complete', 'full-sync'])
  })
  it('uses global search IPC instead of filtering the initial state rows', async () => { const searchMessages = vi.fn(async (input) => ({ items: input.query ? [item] : [], total: input.query ? 1 : 0, nextOffset: null })); await load({ ...mockApi, getState: async () => makeState(), searchMessages }); fireEvent.click(await screen.findByRole('button', { name: /Всё избранное/ })); fireEvent.change(screen.getByPlaceholderText('Поиск по всем сообщениям, темам и тегам…'), { target: { value: 'пределами' } }); expect((await screen.findAllByText('Глобальный результат поиска')).length).toBeGreaterThan(0); expect(searchMessages).toHaveBeenLastCalledWith(expect.objectContaining({ query: 'пределами', limit: 100, offset: 0 })) })
  it('opens a topic through its numeric topicId and exposes only working or disabled controls', async () => { const searchMessages = vi.fn(async (input) => ({ items: input.topicId === 99 ? [item] : [], total: input.topicId === 99 ? 1 : 0, nextOffset: null })); await load({ ...mockApi, getState: async () => makeState(), searchMessages }); fireEvent.click(await screen.findByRole('button', { name: 'Темы' })); fireEvent.click(await screen.findByRole('button', { name: /Дальняя тема/ })); await waitFor(() => expect(searchMessages).toHaveBeenLastCalledWith(expect.objectContaining({ topicId: 99 }))); expect(screen.getByRole('button', { name: 'Карточки' })).toBeDisabled() })
  it('calls credential deletion from the real settings control', async () => { const deleteSecrets = vi.fn(async () => undefined); await load({ ...mockApi, getState: async () => makeState(), deleteSecrets }); fireEvent.click(await screen.findByRole('button', { name: 'Настройки' })); fireEvent.click(await screen.findByRole('button', { name: 'Удалить данные Telegram' })); expect(deleteSecrets).toHaveBeenCalledWith('telegram') })
})
